### ISSUE TITLE
Swide Mode in the IS Compare widget Panning problem

### ISSUE THREAD

**Issue by awetab** [Esri/WAB-Image-Services-Widgets#10]
I am using the IS Compare widget in my image services and when I use the swipe mode,there is panning problem.So,is swipe mode platform or browser dependent or I have configured it wrongly? Please,Anyone who has know how about this,I am in need of your help.

**Comment by kushu493** [comment]
Hi,

Can you please send me an app that you have created, so that i can have a look at what is going wrong.

Regards,

Kushagra

**Comment by awetab** [comment]
Here is the link to the app:http://geodynapp.s3.amazonaws.com/ETH/Comparison%20of%20Addis%20Ababa%201984%20vs%202013/index.html
Let me elaborate more, in my browser,it is working perfectly,but,I attached this link to some one who want to see it and he reported to me as the "swipe mode of the Is compare widget" has panning problem.

**Comment by kushu493** [comment]
Hi,

I have updated the IS Compare widget. You can take this updated widget and plug it in your app.
Thank you for reporting the issue. 
It has been fixed.

Regards,

Kushagra
