### ISSUE TITLE
ISTime Filter Functioning problem with TimeInfo

### ISSUE THREAD

**Issue by awetab** [Esri/WAB-Image-Services-Widgets#11]
Hi,
I want to to detect the change made between two image services(Primary and secondary layers) taken at different dates using the ISChangeDetection widget,and to do that,I have to use the ISTime Filter  widget,but even if the IS Time Select widget is reading the date info,IS Time Filter couldn't read,it says:"TimeInfo is Absent." So,is there anything I have to make change other than I made for IS Time Select widget?Please help me how to solve such problems.

Best Regards,

Awet

**Comment by kushu493** [comment]
For TimeFilter to work u need TimeInfo data present on the service.
By this week end, there will be a major update made to some of the widgets which also includes ISTimeFilter. In the updated version, there is no need for timeInfo data.

For now, if you want to do change detection, you can use IS TimeSelect only. The other widget that you need is IS Layers. Select the first date using ISTime Select and then go to IS LAYERS widget and click on set as secondary layer button. It will push down the first image. Go back to ISTime Select and select other date.
Then go to IS Change detection and click on apply. You have change image.

Regards,

Kushagra
