### ISSUE TITLE
IS Layers not working properly on our Imagery services

### ISSUE THREAD

**Issue by TraceyVG** [Esri/WAB-Image-Services-Widgets#15]
I have created two WebApps: one built on the ArcGIS Online WebMap created for WAB-IS, and one on imagery services stood up my my project team-mates.  The second consists of NITF imagery services on one layer, and elevation (SRTM 30M) on another. 

When attempting to **configure** the IS Layers widget in the two different apps, the ESRI data WebApp simply shows the widget name, icon, the ability to change that icon, and the Webmap Id upon which the app is built. Launching the app and clicking the widget icon works as expected.

In the WebApp built on OUR Image services, things are different from the outset.  When **configuring**, there is no WebMap ID shown, but rather drop-downs to select the primary and secondary layers.  The "loading" wheel spins non-stop, even after selecting Primary and secondary layers. Clicking OK and Launching the app looks good until I click the IS Layers icon, when I am greeted with a Create Widget error.

I have removed the widget, reloaded the WAB, added the widget back in, and nothing changes.  

Any suggestions?

**Comment by kushu493** [comment]
IS Layers widget has been modified. It no longers takes Webmap ID as an input. 
Can you share the webmap with me or the image services links?

**Comment by kushu493** [comment]
Does your service has "Service Data Type" property? If not, the widget won't work.

**Comment by TraceyVG** [comment]
That makes sense, since the App built on ESRI webmap has the OLD IS Layers widget, and the app built on our image services has the new version.  But sadly, it is the new version that isn’t working for me.  I will ask Roslyn about sharing the webmap or image services links.  I’m new at this government contract thing, and am not sure how that works.

Is the requirement for the "Service Data Type" property new to this version?  If so, that could be the issue, since I believe this widget worked for me before, though I am not 100% sure that was on our data as well as ESRI data.

**Comment by kushu493** [comment]
Tracey,
I made changes to ISLayers widget.
You can download the widget. It should work now.

**Comment by TraceyVG** [comment]
Thank you; that seems to have fixed it!
