### ISSUE TITLE
IS Compare window gets in the way.

### ISSUE THREAD

**Issue by TraceyVG** [Esri/WAB-Image-Services-Widgets#17]
When testing the IS Compare widget on our data, I find that the functionality is very good, however, the window describing the type of swipe and the layers being compared blocks the view of the display.

If I close the window, the widget turns off.

I can drag the corner to make the window larger, but not smaller.

The only workaround I have found is to drag the whole window partially off-screen, but that seems cumbersome.  Is there another way to remove this window that I have missed?  I would really like to include this widget in a demo I am doing next week, and would like it to be as clean and simple as possible.

Thank you.

**Comment by kushu493** [comment]
Which theme are you using? Most of the web appbuilder themes have a option of minimize. When you click on the minimize button (right next to the close button)it minimizes the window. The widget will still be on. So you can easily do swipe.

![image](https://user-images.githubusercontent.com/11013183/27747393-00ae95ca-5ddc-11e7-9a32-02e6e07ba4f2.png)

In this image you can see the minimize  window button next to close button.

**Comment by TraceyVG** [comment]
Oh, I didn't think of changing themes.  I am using the foldable theme, which does not have the minimize button. 

 I was using the foldable wrapper theme before, but it does not offer the extent navigation widget, and that one is important to have.  I guess I have to do more studying about the themes and maybe how to create my own that has everything I need in it.  In the mean time, do you have a suggestion for a better theme for me to use if I want to use the following widgets: 

IS Image Date
Bookmarks
Swipe
Add Data
IS Compare
IS Image Selector
IS Profile
IS Layers

**Comment by kushu493** [comment]
Foldable theme has the minimize button. Can you please check the version of web appbuilder you are using. The latest one is 2.4. 
For your demo, you can use launchpad theme . It allows you to open more than one widget at a time.

**Comment by TraceyVG** [comment]
I figured it out. 
When I am editing the app in Web AppBuilder, the IS Compare widget does not have the minimize button.  But when I _launch_ the app, it is there.  My apologies for the confusion.  I am going back and forth a lot today, and I confused myself.

Thank you for the tip on the Launchpad theme; I will give that a try.

I appreciate your willingness to help.

**Comment by TraceyVG** [comment]
Kushagra, as I was practicing my presentation today, I discovered the IS Compare widget is not giving me the minimize option like it did Friday.  I am using the 2.4 version of WebAppBuilder, and I double checked that the theme is Foldable.  I considered that the fact that I had practiced a variety of widgets in the web app prior to the IS Compare, which may have caused it to malfunction.  So I closed everything, and re-launched the App, going directly to the IS Compare, and there was still no minimize button, even though it was there when we discussed it Friday.

I tried removing and re-adding the widget, and still no minimize button.  I created a brand new web app, and there was still no minimize button, even when I tried different themes.

The only thing that finally worked was when I removed the widget from the App screen (where it is shown in the WAB-IS User document for version 2.2) and added it to the _header_ instead.  

Is it because I am using version 2.4 that the widget doesn't work where it is shown in the guide, which was written for v2.2?  Will a new User Doc be coming out soon, with updated info for the IS widgets?

Another interesting question is why did it work Friday from the screen, albeit briefly?

**Comment by kushu493** [comment]
Tracey,

Minimize button is only available when you load the widgets in Header controller. When you load them as on screen widget, most of theme doesn't have minimize button. Its better if you load compare in header controller. 

Yes, the new document for Wabis 2.0 will be released soon on github. 

Again you can modify the themes according to your requirements. If you want ISCompare as on-screen widget, then you will have to modify the theme to add minimize button.

**Comment by TraceyVG** [comment]
Thank you for that clarification, Kusghagra.  So I now have the IS Compare loaded in the Header Controller, so the minimize button works as expected.  Now I am finding an additional issue with this widget, which, of course may be a user error, since I don't have current documentation for the widget.

When configuring IS Compare, the user has the choice between setting this to work with "transparency slider and vertical swipe"  OR "horizontal swipe and vertical swipe."  However, regardless of which way the widget is configured, the only tool provided to user upon activation of the widget is the vertical swipe.  Am I doing something wrong?

**Comment by kushu493** [comment]
Transparency slider or horizontal slider will  only  show up in the app if there is result layer. Vertical swipe will always compare between primary and secondary, secondary and basemap, or primary and basemap.

If you have result layer, then you can compare three layers at the same time using vertical swipe and horizontal swipe (or transparency slider). 

So in your case, only vertical swipe will be available.

New document will explain the widget functionality more in detail.

**Comment by TraceyVG** [comment]
Ah, now I understand.  It will be very nice to be able to compare three layers simultaneously!  Thank you.  I look forward to the new documentation coming out.
