### ISSUE TITLE
IS widgets do not work when grouped together

### ISSUE THREAD

**Issue by f-tonini** [Esri/WAB-Image-Services-Widgets#18]
As you state in your documentation, IS widgets do not work when grouped together. I am not sure how easy this would be to fix and upgrade, but it seems really needed to avoid cluttering when deploying several of your IS widgets alongside other widgets inside a custom web app.

**Comment by ewindahl** [comment]
Hi Francesco, look for a fix for this problem sometime in the next few weeks. Thanks!

**Comment by kushu493** [comment]
Hi Francesco, 

Widgets work when grouped together. Only issue is with Foldable Wrapper Theme (available with this repository). You can use any other theme in Web AppBuilder.


Thanks,
Kushagra

**Comment by f-tonini** [comment]
Thank you for your email Kushagra, that is good news to hear then! Can you confirm all IS widgets are compatible with latest 2.5 WAB Dev Edition version?

Thank you,
Francesco

**Comment by kushu493** [comment]
Yes. They are compatible with 2.5 WAB version.
