### ISSUE TITLE
Browser compatibility?

### ISSUE THREAD

**Issue by TraceyVG** [Esri/WAB-Image-Services-Widgets#19]
I apologize if this question has already been answered elsewhere:

Are the WAB-IS widgets (and the Web Apps built from the Web AppBuilder) designed designed for and tested within particular browsers?  Are there any known issues with any particular browsers?  I am particularly interested in Chrome, Firefox, and IE.

**Comment by kushu493** [comment]
Yes. WABIS widgets are compatible with all the browsers (Chrome, firefox,Safari and IE).
