### ISSUE TITLE
What version of Web AppBuilder Dev?

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/WAB-Image-Services-Widgets#2]
What version of Web AppBuilder Dev are the current widgets certified to work with?  I have v2 and can't seem to get the widgets to work.  By "not work" I mean, I can add the widgets to my app using the custom theme you guys provided, but when I click on the widgets (all of them) they don't do anything.  When I try to edit the properties of the widgets I am not presented a configuration dialog, it looks like this:
![image](https://cloud.githubusercontent.com/assets/4732590/14323604/00d6e930-fbd6-11e5-8d48-662ff39ca278.png)

Note: I have not tried these current widgets in previous versions of web appbuilder.

Thanks in advance!

**Comment by kushu493** [comment]
Widgets will work with v2.0. Custom theme was certified to work with v1.3. It has been updated to v2.0. You can download the updated theme files.
