### ISSUE TITLE
IS Spectral Profile RequestError: Unable to load

### ISSUE THREAD

**Issue by f-tonini** [Esri/WAB-Image-Services-Widgets#20]
I included the IS spectral profile widget into my own web app. When I click a point on the map, with the Landsat MS layer specified as "primary" inside the IS Layers widget, I wait for a few minutes and eventually I receive the following error message:

RequestError: unable to load 
//landsat2.arcgis.com/arcgis/rest/services/Landsat/MS/ImageServer/identify?f=json&geometry=%7B%22x%22%3A3502501.4527257946%2C%22y%22%3A3597726.8737750864%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%7D%7D&returnGeometry=false&returnCatalogItems=true&renderingRule=%7B%22rasterFunction%22%3A%22None%22%7D&geometryType=esriGeometryPoint&pixelSize=%7B%22x%22%3A30%2C%22y%22%3A30%7D status: 0

I try multiple points in different countries, with the same primary layer selected but it keeps failing. Is this a bug or a misunderstanding of its use on my end?

**Comment by kushu493** [comment]
I think you are using the wrong widget. IS Spectral Profile has been deprecated. The replacement of it is IS Profile widget.
Its not a bug, request is getting timed out. Server is taking a long time to return the pixel values. 
In new IS Profile widget, i making a different request which is much faster and chances of it getting timed out are also less. 

Also i would advice only to use the widgets that are available with Wabis 2.0. Most of the WABIS 1.0 widgets have been deprecated. 
Best if you can go through documentation to get the idea what has changed in Wabis 2.0 as compared to Wabis 1.0

**Comment by f-tonini** [comment]
I see, I must have had my fork synced to master instead of WABIS2.0, hence reading the documentation of the older version. I will update my widgets (and fork) and will let you know if I still experience any errors. Closing the case for this error.
