### ISSUE TITLE
Icon selection area has shrunk dramatically in HeaderController

### ISSUE THREAD

**Issue by TraceyVG** [Esri/WAB-Image-Services-Widgets#21]
I've been working with a WebApp I created a few weeks ago, and made some recent changes that seem to have caused a weird change in the HeaderController widgets.  I can only select them from a very small zone along the bottom of each widget icon.  I have been tweaking some config files, but don't know why this would have happened as a result of those changes.

Everything was working normally until I changed the index numbers to rearrange some of the IS and other widgets in the HeaderController, while also bumping up the PaddingRight for the search window to move it to the left side of the widgets.

Is anyone aware of what may have caused this?

**Comment by TraceyVG** [comment]
OK, Upon further examination, I think I caused this when I moved the Search window (at customer's request) to the left of the IS widget icons.  The only way I could find to do it was to increase the paddingRight value, but what I didn't realize is that this method is basically just stretching the search bar across all icons, even though it does not visibly cover them.  Consequently, the icons can only be selected from the tiny margin of each that peeks out from above or below the invisible padding for the search window.

So my new question is: from within the foldable theme, with the layout where the search window is adjacent to the HeaderController, how can I move the HeaderController to the right of the search window without obstructing access to the widgets contained by the HeaderController?

**Comment by kushu493** [comment]
If you know the width of your header controller then apply the padding right to search container.

**Comment by TraceyVG** [comment]
I tried that, but found that the padding actually "covered" the header controller, making all widgets unselectable, except for a very thin margin at the tops and bottoms.  Our lead developer found another way to get the search window to move, but if the app window is not wide enough, the widgets begin to tuck behind it, and if the window is not tall enough, it actually drops the search window down below the header controller and to the right, which is very odd.  Given that neither of us have created a new layout before, and the time it would take to learn the process and then do it may be outside the scope of what the customer is ready to pay for, we are returning the issue to the customer, and asking them if they would consider just letting us put the search window back to the right of the header controller where the layout wants it.  If it turns out that he really wants it to the left, we will share whatever layout we end up having to create.
