### ISSUE TITLE
Questions on the IS Display Order widget

### ISSUE THREAD

**Issue by TraceyVG** [Esri/WAB-Image-Services-Widgets#22]
When testing different mosaic methods, I discovered something odd, and wanted to clarify whether this is how the widget is supposed to operate or not.

For most mosaic methods, there is a tool tip Drop down button that offers the option to reverse the order, as well as selecting a mosaic operation.

The widget.html file (if I read it correctly) makes it appear that this button should show up for all mosaic methods, and that it should offer the option to reverse the order for all methods except the Defined Seamlines method.  

The reverse the order checkbox does not show up for the seamlines (as it shouldn't), but the the 'Closest to Viewpoint' method does not even have the Tool tip dropdown button, which I believe it should.

Is this a bug, or is there a reason one does not have access to the mosaic operations or reverse order for the Closest to Viewpoint mosaic method?

Thank you for your time.

**Comment by kushu493** [comment]
Hi Tracey,
It's not a bug. I had specifically removed the tooltip dropdown button for this mosaic method. But realizing that user would like different mosaic operations and reverse order capability i have added the tooltip dropdown back.

**Comment by TraceyVG** [comment]
Thank you, Kushagra!
