### ISSUE TITLE
Image Discovery Functionality?

### ISSUE THREAD

**Issue by brianjbaldwin** [Esri/WAB-Image-Services-Widgets#25]
Apologies if it's obvious, but on reading through the tool descriptions, I can't find a replacement for the Image Discovery widget: https://github.com/Esri/image-discovery-app-js

The Image Discovery repo is no longer maintained and directs users to this site.

Required functionality is for a user to specify an AOI and then have a result return all of the image services that are present in that area, with the ability to preview, or add them to the map.

**Comment by PBecker92373** [comment]
Check out this [ImageDiscovery widget](https://github.com/Esri/defense-solutions-proofs-of-concept/tree/master/widgets/ImageDiscovery)  Its a widget for WebAppBuilder
