### ISSUE TITLE
IS Renderer

### ISSUE THREAD

**Issue by vxsunstriderxv** [Esri/WAB-Image-Services-Widgets#3]
Could the IS Renderer widget be set up to allow users to select the layer they want to change the render on, ie a drop down list of all the image services available in the app?  At the moment a user is only able to interact with the top layer but it would be useful if other layers functions could be accessed and changed too.

Also, is it possible to configure what renderers are available to the user when configuring the app in WAB?  

Thanks

**Comment by kushu493** [comment]
No, IS Renderer widget will only have the renderers available on the top layer in the drop down list. If the user wants to change the layer, he/she can use IS Layers widget. IS Layers widget will list down all the layers in the app. 

The solution to your situation  is to have both the IS Layers and IS Renderer widget in the app. User can set the top layer using IS Layers widget. IS Renderer widget will automatically update its drop down list every time the top layer is changed.

No, you cannot configure what renderers will be available to the user while configuring the app as IS Renderer widget gets all the renderer info from the image service of the top layer during run time.
