### ISSUE TITLE
IS Classification - Image Services published on ArcGIS Server v10.5 or higher are supported

### ISSUE THREAD

**Issue by mkoon22** [Esri/WAB-Image-Services-Widgets#31]
When attempting to run the "IS Classification" widget - Image Services published on ArcGIS Server v10.5 or higher are supported. Has this been fixed. What is the reason for this not working on older AG server versions?

**Comment by kushu493** [comment]
Hi,

There was an issue in older ArcGIS Server versions for Classification method (classify request). The issue was fixed in 10.5. So to do classification you will require version >10.5.

Thank You.
