### ISSUE TITLE
IS Catalog widget fails to download the images from an Image Service

### ISSUE THREAD

**Issue by jklausner4** [Esri/WAB-Image-Services-Widgets#36]
When first trying to download individual images from an image service using IS Catalog widget, the download was successful.  
After that when clicking on an image to download, the browser will prompt a HTTP ERROR 400 each time. The issue happened with multiple image services with download enabled. 
WAB 2.11 edition was used.

An ESRI analyst assigned to this case was able to reproduce the same issue using the IS Catalog widget (Esri Case #02461170). WAB 2.12 edition was used by ESRI analyst.

**Comment by priya4991** [comment]
@jk518008 Can you elaborate a bit? It worked the first time and it didnt after that?

**Comment by jklausner4** [comment]
I published a different image service today **registering the data with the Image Server**, but I am still getting the same error as before, even when trying at the first time. 

ESRI analyst said that he was able to download images using IS Catalog widget **only after he chose to copy the data over to the server** so that might be the issue. The problem for me is that my images including the mosaic dataset and overviews size up to few TB so that doesn't make sense to copy them to the server.

**Comment by priya4991** [comment]
Okay. Thanks, we will look into this.

**Comment by gcampanile** [comment]
Hi,
you should modify the widget so to convert the image to another format, example: format=JP2:Conversion (see https://developers.arcgis.com/rest/services-reference/download-rasters.htm) . In this case the server wilkl convert the source image and downstream it, instead of tryting to access the original file.

**Comment by jklausner4** [comment]
@gcampanile Thank you for the response. Can you please elaborate on how I can change the widget to do that? What do I need to change in the code?

Thank you

**Comment by gcampanile** [comment]
In the ISCatalog\base\CheckoutWidget\base\Download\ImageryDownloadWidget.js, lines 110-114 :
```
                            params = {
                                f: "json",
                                rasterIds: currentDownloadItemObj.objectIds.join(","),
				format: "JP2:Conversion"
                            };
```
Of course if you need something different from JP2 you must change the string or use a parameter.
Gianni

**Comment by priya4991** [comment]
@jk518008 have you been able to try the fix mentioned above?

**Comment by jklausner4** [comment]
Sorry for the late response.

I changed the code as suggested and this time it looked like it was really processing for about 30 secs and then the file was ready to download  :
![image](https://user-images.githubusercontent.com/59484272/93520578-8d4b2c00-f8e3-11ea-88b4-8ddea7c2d610.png)

When I click to download the image, I am getting the following error:

![image](https://user-images.githubusercontent.com/59484272/93520981-32660480-f8e4-11ea-836b-330360d409b9.png)

What can cause this error?
