### ISSUE TITLE
Issue using ChangeDetection widget

### ISSUE THREAD

**Issue by kv5784** [Esri/WAB-Image-Services-Widgets#41]
I have tried using this widget but it constantly kept loading so I tried to investigate issue furthur using browser developer tool.  From what I understand, the error has something to do with strings.js file in this path: _/apps/webappbuilder/stemapp/widgets/ISChangeDetection/nls/strings_
but I really don't know what's wrong with this file (please remark that I have very little knowledge on programming).
Please refer to the image below for the error message:
![DeveloperTool_2](https://user-images.githubusercontent.com/74392730/99036587-87588b00-25b4-11eb-8874-4516ee39b0a4.jpg)

Please kindly help me resolve on this issue.

**Comment by abhiataero** [comment]
@kv5784 will have this fixed

**Comment by priya4991** [comment]
@kv5784 we have updated the widget. Can you please try it again? Let us know if you face any issues.
Thanks.

**Comment by kv5784** [comment]
@priya4991 Thank you so much for your help. I am now able to use the widget.
