### ISSUE TITLE
Can we use the IS ChangeDetection widget with imagery from drone?

### ISSUE THREAD

**Issue by nuttawat5931** [Esri/WAB-Image-Services-Widgets#44]
I was tested ISChangeDetection widget with a multi band imagery service from UAV as mosaic dataset  which is published from ArcGIS Pro 2.6. My workflow is using a vegetation index method with Difference Mask mode on the widget then select an IR and R band as suggest then apply. However, the result is nothing change to a map, no area decease or increase in the result.

best regards,
nuttawat

**Comment by nuttawat5931** [comment]
For more information, I am able to use a change detection tool in Image Mask (configurable apps in Enterprise portal 10.8.1) with the same multi-band imagery service from UAV which is tested in WABIS widget to see a change in an increasing or decreasing area change. But I can not calculate a change result in IS ChangeDetection widget in Web AppBuilder. Not only to imagery service from UAV but using a  [landsat/MS](https://landsat2.arcgis.com/arcgis/rest/services/Landsat/MS/ImageServer) service is unable too. 

Is these widget is usable or not? If yes, could you provide the complete workflow of using the IS ChangeDetection widget?
Because I was follow the instruction provided in a PDF as well. But it still can not see a different change in a result.

**Comment by nuttawat5931** [comment]
This is a video for Chang Detection from a configurable apps. <https://drive.google.com/file/d/110MRMzOOHMcYWx2FLN09rFKOmJtcMkJl/view?usp=sharing>

and another one is a video using ISChangeDetection widget in Web AppBuilder for developer edition <https://drive.google.com/file/d/1Fb1yKGe0yjXgwVti1UZlEOqPgFgfiq62/view?usp=sharing>

**Comment by priya4991** [comment]
@nuttawat5931 Thank you for reporting this. We will look into this and get back to you soon.

**Comment by nuttawat5931** [comment]
hi @priya4991 If any updates please reach me ASAP. Thank you.

**Comment by priya4991** [comment]
@nuttawat5931 we are looking into this with priority. Will get back to you in a day.

**Comment by priya4991** [comment]
@nuttawat5931 I just went through your video, and tried the widget on Multispectral Landsat. You are missing a step in your workflow.
After you set a particular image as Secondary Image, you have to then choose the Primary Image. And then you have to perform change detection. 
When I don't select a primary image after selecting the secondary image, that is when I run into your problem. Please try this out and then get back to us if you face any issues.

**Comment by nuttawat5931** [comment]
Many thanks @priya4991 I am able to run the widget now.

**Comment by priya4991** [comment]
@nuttawat5931  great! :) if the widget is working, and you are not facing any more issues, please do close this issue. Thank you.
