### ISSUE TITLE
IS Renderer should report what the active layer is and allow user to change the target

### ISSUE THREAD

**Issue by sirws** [Esri/WAB-Image-Services-Widgets#5]
It would be really useful if a widget, like IS Renderer, would report what the active layer is.  Perhaps something like this:
![image](https://cloud.githubusercontent.com/assets/793576/17489830/bb2deef2-5d54-11e6-812e-4d87d830f523.png)
Secondly, it would be great if it also allowed you to change the active layer in the widget instead of having to go to the IS Layers widget.
I can see having the option to select the active layer as a dropdown in the widget and having it automatically move the layer to the top of the TOC.

Thanks!
Scott

**Comment by kushu493** [comment]
Scott,

Your suggestion of broadcasting active layer in IS Renderer seems plausible. **I have made the change in the widget and updated it on Github.**

Purpose of IS Renderer widget is to list down all the renderers available on the image service and allow the user to change it. Ability to change/switch active layer is completely different functionality and it doesn't lie in the scope of IS Renderer widget. 
Not only Renderer widget but all the other widgets in this repo depend on IS Layers. 

If you want changing the active layer feature, best thing is to create a group of widgets. Basically you put Renderer and IS Layers widget in a group, thus making them work as one widget. Web AppBuilder has this feature of creating a group of widgets.
Link - https://developers.arcgis.com/web-appbuilder/guide/widgets-tab.htm
Below is  an image of the group created using IS Renderer and IS Layers. You can give any name to the group if you want. 

Regards,
Kushagra

**Comment by kushu493** [comment]
Scott,

Your suggestion of broadcasting active layer in IS Renderer seems plausible. I have made the change in the widget and updated it on Github.

Purpose of IS Renderer widget is to list down all the renderers available on the image service and allow the user to change it. Ability to change/switch active layer is completely different functionality and it doesn't lie in the scope of IS Renderer widget. 
Not only Renderer widget but all the other widgets in this repo depend on IS Layers.

If you want changing the active layer feature, best thing is to create a group of widgets. Basically you put Renderer and IS Layers widget in a group, thus making them work as one widget. Web AppBuilder has this feature of creating a group of widgets.
Link - https://developers.arcgis.com/web-appbuilder/guide/widgets-tab.htm
Below is an image of the group created using IS Renderer and IS Layers. You can give any name to the group if you want.
![image](https://cloud.githubusercontent.com/assets/11013183/17506921/b1d7020c-5e1d-11e6-82bc-dc7d559b9d37.png)

Regards,
Kushagra

**Comment by sirws** [comment]
Thanks for the fix and the ideas!
