### ISSUE TITLE
IS Layers widget not honoring webmap layer names and seems to be changing them.

### ISSUE THREAD

**Issue by sirws** [Esri/WAB-Image-Services-Widgets#6]
http://nwdemo1.esri.com/lidarexplorer2/

Load the app.  Layer List shows the appropriate layer names.
![image](https://cloud.githubusercontent.com/assets/793576/17542881/545f370c-5e81-11e6-9a82-8e2f79d4c7e4.png)

Open the IS Layers/IS Renderer Group:
![image](https://cloud.githubusercontent.com/assets/793576/17542909/99df515e-5e81-11e6-83eb-c6c7799bf5e3.png)

Switch back to Layer List:
![image](https://cloud.githubusercontent.com/assets/793576/17542924/ab5a2c92-5e81-11e6-97cc-20dbadb995d6.png)

Notice the "WA State DTM (Terrain)" has changed.

Also, it appears the layers are repeated for some reason in the IS Layers control.
![image](https://cloud.githubusercontent.com/assets/793576/17542988/2364b05e-5e82-11e6-81db-811eb4b155cd.png)

Finally, why does the ISLayers control show layers that aren't image services?  This is showing map service layers as well.  I would expect to only see two layers in it.

Here is the source webmap:
http://wadnr.maps.arcgis.com/home/webmap/viewer.html?webmap=aaf626bc4f9b435199eae80f0bdb7fbb

**Comment by kushu493** [comment]
Scott,

1) Layers are coming twice in IS Layers dropdown - Widget reads both the layers present in the webmap loaded with the app, along with the webmap id provided in the configuration of ISLayers widget. I would suggest you read the doc for this as it explains the functionality of the IS Layers widget. To solve your problem, go to root folder of the app, then go to configs/ISLayers/config_IS Layers.json file. Open the file and make the value of webmapId as "".

2) Title getting change in the LayerList and reading of map service issue fixed. I have updated the file ISLayers folder on Github. You can take new updated code from there.


Regards,

Kushagra

**Comment by sirws** [comment]
Thanks Kushagra!  I will definitely take a look at the doc again.

The changes look pretty good.  You may want to report the layer name the same in the IS Renderer widget:

![image](https://cloud.githubusercontent.com/assets/793576/17559906/c97ed8fa-5ed4-11e6-966f-93aa5f74adc0.png)

It should say "WA State DSM (Surface)" just like the layer name.

Thanks!
Scott
