### ISSUE TITLE
Foldable wrapper theme does not appear and IS Spectral profile does not work

### ISSUE THREAD

**Issue by cuevasgonzalez** [Esri/WAB-Image-Services-Widgets#8]
Hi, 

I am trying to implement the IS Spectral profile but nothing happens when I select a point on the map. The IS Renderer works just fine. I am working with a raster dataset with 26 images and webappbuilder v2.1.
Besides, I cannot see the Foldable Wrapper Theme (although it is deployed in the client/stemapp/themes folder) so I am implementing IS Spectral profile and IS Renderer in Foldable Theme. Could this be an issue?

Thanks in advance.
Maria

**Comment by kushu493** [comment]
Hi Maria,

Can you please share your app with me? If not, can you share the raster dataset?
I can have a look at it and then provide you appropriate solution.

Regards,
Kushagra

**Comment by cuevasgonzalez** [comment]
Hi Kushagra,

This is a test app I created only with the IS Spectral profile and Renderer widgets. Besides, I only added the raster dataset. The complete app have additional widgets and vector layers. 

Many thanks!
Maria

[TEST_Spectral_profile.zip](https://github.com/Esri/WAB-Image-Services-Widgets/files/479727/TEST_Spectral_profile.zip)

**Comment by kushu493** [comment]
Hi,

Can you please share the app's webmap publically as i am not able to access it.

Regards,
Kushagra

**Comment by cuevasgonzalez** [comment]
Done. Sorry.

**Comment by kushu493** [comment]
Hi Maria,

Spectral profile will only work for landsat/sentinel data.

Regards,
Kushagra

**Comment by cuevasgonzalez** [comment]
Hi Kushagra,

Thanks for letting me know. Is there any option I can change or add so it can work with any custom raster dataset? 

Thanks,
Maria

**Comment by kushu493** [comment]
Hi Maria,

I can make the spectral profile work for this specific dataset and give it to you. let me know.
 Anyways i will be updating the widgets in two or three weeks to make them more user friendly and allowing the users to configure them.

Regards,
Kushagra

**Comment by cuevasgonzalez** [comment]
Hi Kushagra,

It would be great if the widget could work for this dataset but I am not sure whether it involves a lot of work or is something that you can change easily. If it is too much work I could wait for the update.

Many thanks for your help,
Maria

**Comment by kushu493** [comment]
Hi Maria,

I updated the Foldable Wrapper Theme. Can you take the updated version from Github and copy it to  client/stemapp/themes folder. Make sure you copy the theme first and then run the startup.bat file.

**Comment by cuevasgonzalez** [comment]
Hi Kushagra,

Thanks a lot for this updated version. However, I am having trouble...it is not working. Do you know what the problem might be?

![isspectralprofile](https://cloud.githubusercontent.com/assets/22051244/18741465/afffe322-80af-11e6-84d7-1e2902513055.png)

**Comment by kushu493** [comment]
Hi Maria,

Update was made for the Foldable Wrapper Theme, not the IS Spectral Profile widget.
The widget will still not work with your dataset.

Regards,

Kushagra

**Comment by cuevasgonzalez** [comment]
Ahh, OK. Sorry for the misunderstanding, The Foldable Wrapper Theme works fine.
Many thanks.
Maria

**Comment by kushu493** [comment]
Hi Maria,

Just wanted to let you know that IS Spectral Profile along with some other widgets has been updated.
Also i am closing this issue.

Regards,
Kushagra  Patel
