### ISSUE TITLE
IS Time Select Widget is not working with year field

### ISSUE THREAD

**Issue by awetab** [Esri/WAB-Image-Services-Widgets#9]
I am beginner for WABIS Widgets and I am trying to configure IS Time Select widget with an image service which has year as a field but when I try to configure it pop ups as shown below:
![its](https://cloud.githubusercontent.com/assets/20126043/20875336/f504841e-baca-11e6-9fd2-a2e3b6215b4c.PNG)
So, does IS Time Select Widget always work with date format only or it can work with year too? I need any help related with this guys.

**Comment by kushu493** [comment]
Hi,

It seems that your service does not have any date Field.  Therefore, the dropdown list is empty.
Basically the widget gets all the field with type as "esriFieldTypeDate" and populate them in the list. Then the user can select the date field which is appropriate.
So you need to have a date field type in order for this widget to work.
In your scenario, it seems year is an string field type or an integer field type.

Regards,

Kushagra

**Comment by awetab** [comment]
Kushagra,
Thank you very much for your help. And I want one favor from you, but it is not an issue,could you share me any reference which teaches how to develop WABIS Widgets step by step(Specially on how to access map layers with WABIS Widget and create an effect on the layers),I am so interested to work in this.

Thanks again
Awet

**Comment by kushu493** [comment]
Awet,

All the widgets are developed using ArcGIS API for Javascript. 
https://developers.arcgis.com/javascript/3/jsapi/
This API will help you in interacting with map layers and creating an effect on layers.

For developing Widgets just go through this link - https://developers.arcgis.com/web-appbuilder/guide/naming-conventions.htm

This guide will help you in understanding the schema of the widgets and their development.

Regards,

Kushagra

**Comment by awetab** [comment]
Thank you very much for your help and consideration.

Best Regards,

Awet

**Comment by kushu493** [comment]
Awet,

If it's okay with you, can you please close this issue.

Thanks.

Regards,
Kushagra

**Comment by awetab** [comment]
Ok, I will close it but I need one more help.
I have changed the data type of the date field to date and now it is being read by the IS Time Select widget but the problem is,when I navigate from date to date using the Time Selector,no image service(layer) change is being seen.the image service being seen is constant which is the first one,so,could you help me how to figure out it?

Regards,
Awet

**Comment by kushu493** [comment]
What Mosaic Method are you using?

Regards,

Kushagra Patel

**Comment by awetab** [comment]
sorry to say that but,I am accessing from ArcGIS online and I asked them to change the data type of the date(year) field based on what you informed me yesterday,so,I have know how on the mosaic type they use but on my widget configuration I used as shown below:
![is time select config](https://cloud.githubusercontent.com/assets/20126043/20923745/f8bf207e-bbbe-11e6-92fc-bedc1f206d12.PNG)

Thank you very much for your priceless help.

Regards,

Awet A.

**Comment by kushu493** [comment]
can you please check the "Check to select Mosaic Method from the panel" option. 
And then send me the app with this widget.

According to your requirement, i think you should select the other option in Mosaic Method i.e. Lock to best. 

Regards,
Kushagra

**Comment by awetab** [comment]
Thank you very much,mistake corrected.
